// <auto-generated />
using System;
using MDA.Restaraunt.Messages.DbData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDA.Restaraunt.Messages.DbData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("MDA.Restaraunt.Messages.Repository.BookingRequestModel", b =>
                {
                    b.Property<int>("BookingRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingRequestId");

                    b.ToTable("BookingRequestModels");
                });
#pragma warning restore 612, 618
        }
    }
}
